### PR TITLE
fix: io-engine clippy warnings

### PR DESCRIPTION
**Pull request by hrudaya21**

### CODE REVIEW

**Comment by hrudaya21** [comment]
bors try

**Comment by dsavitskiy** [comment]
bors try

**Comment by hrudaya21** [comment]
bors try

**Comment by dsavitskiy** [comment]
bors try

**Review by dsavitskiy — APPROVED** [review]

**Comment by hrudaya21** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]

**Review by mtzaurus — APPROVED** [review]

**Comment by hrudaya21** [comment]
bors merge

**Pull request merged**
