### PR TITLE
test(e2e): tag CI images only on success

### PR DESCRIPTION
**Pull request by chriswldenyer**
Builds from develop are pushed to the CI registry before the e2e test is run.
However we should tag the images as 'nightly' only when the test succeeds.
This ensures the mayastor-e2e-self-ci runs use images known to have passed CI.

### CODE REVIEW

**Comment by chriswldenyer** [comment]
bors try

**Comment by chriswldenyer** [comment]
bors try

**Comment by chriswldenyer** [comment]
bors try

**Comment by chriswldenyer** [comment]
bors try

**Comment by chriswldenyer** [comment]
bors try

**Comment by chriswldenyer** [comment]
bors try

**Review by blaisedias — APPROVED** [review]
Looks okay to me.

**Review by tiagolobocastro — APPROVED** [review]

**Comment by chriswldenyer** [comment]
bors merge

**Pull request merged**
