### PR TITLE
chore(nightly): update nix rust nightly

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Update the rust nightly toolchain

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors try

**Review by jkryl — APPROVED** [review]
🎉

**Review by jonathan-teh — APPROVED** [review]

**Comment by gila** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
