### PR TITLE
Jenkinsfile simplification

### PR DESCRIPTION
**Pull request by bobek**
This patch tries to keep the original behavior, but simplifies the Jenkinsfile by
- scheduling runs only for `develop` branch
- guarding `develop` branch from `jenkins.branch.BranchIndexingCause` by aborting such jobs
- making sure, that we descent the list of previous jobs to find the closes non-aborted job

This allowed for simplification of the `when{}` statements.

### CODE REVIEW

**Review by gila — APPROVED** [review]

**Comment by bobek** [comment]
bors merge

**Review by arne-rusek — APPROVED** [review]

**Comment by bobek** [comment]
bors merge

**Review by jkryl — APPROVED** [review]

**Comment by arne-rusek** [comment]
bors retry

**Comment by bobek** [comment]
bors retry

**Pull request merged**
