### PR TITLE
style(lint): lint commits messages

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Add github action to lint PR commits and the PR itself.
Add pre-commit hook to lint commit messages locally.

### CODE REVIEW

**Comment by mtzaurus** [comment]
@tiagolobocastro, just a small nit/suggestion: shall we rename commitlint.yml to reflect the fact that it deals only with PR linting (as per on: "pull_request") ? I mean, add 'pr' or so to the name of the file to let distinguish between any other commit linting actions which we might have in the future.
Otherwise, LGTM.

**Review by paulyoong — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
> @tiagolobocastro, just a small nit/suggestion: shall we rename commitlint.yml to reflect the fact that it deals only with PR linting (as per on: "pull_request") ? I mean, add 'pr' or so to the name of the file to let distinguish between any other commit linting actions which we might have in the future.
> Otherwise, LGTM.

Sure, done!

**Review by mtzaurus — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
