### PR TITLE
fix(rpc): added lock manager

### PR DESCRIPTION
**Pull request by mtzaurus**
Lock manager added.

Signed-off-by: Mikhail Tcymbaliuk <mtzaurus@gmail.com>

### CODE REVIEW

**Comment by mtzaurus** [comment]
bors try

**Comment by mtzaurus** [comment]
bors try

**Comment by mtzaurus** [comment]
bors try

**Comment by mtzaurus** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]

**Review by avishnu — APPROVED** [review]

**Comment by mtzaurus** [comment]
bors try

**Comment by mtzaurus** [comment]
bors merge

**Pull request merged**
