### PR TITLE
Use clippy and fmt rules from rust stable

### PR DESCRIPTION
**Pull request by tiagolobocastro**
refactor(fmt): use fmt style from rust stable
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    refactor(clippy): use rust stable and remove exceptions
    
    Switch to rust-stable and remove most clippy exceptions from linter script.
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors try

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by sinhaashish — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
