### PR TITLE
test(py): add test_config.ini

### PR DESCRIPTION
**Pull request by gila**
This configuration file allows us to fine-tune the test suite such that
they can be run easily in CI but also, locally if resources allow it.

### CODE REVIEW

**Review by mtzaurus — APPROVED** [review]

**Review by paulyoong — APPROVED** [review]

**Comment by gila** [comment]
bors merge

**Comment by gila** [comment]
bors cancel

**Comment by gila** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
