### PR TITLE
Cherry-pick #1443

### PR DESCRIPTION
**Pull request by tiagolobocastro**
ci: cleanup docker on start and exit

### CODE REVIEW

**Review by hrudaya21 — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
