### PR TITLE
feat(nexus): improving nexus fault injection

### PR DESCRIPTION
**Pull request by dsavitskiy**

### CODE REVIEW

**Comment by dsavitskiy** [comment]
bors try

**Comment by dsavitskiy** [comment]
bors try

**Comment by dsavitskiy** [comment]
bors try

**Comment by dsavitskiy** [comment]
bors try

**Comment by dsavitskiy** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]

**Review by dsharma-dc — APPROVED** [review]

**Comment by dsavitskiy** [comment]
bors merge

**Pull request merged**
