### PR TITLE
test: preserve path when using sudo

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Adds script (nix-sudo) which gets the full path of the nix binaries and
runs them with sudo -E.
Hopefully this will help devs which use safe paths without the nix store.

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by hrudaya21 — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
Failed resize test, should be fixed on develop now, and so...
bors merge

**Pull request merged**
