### PR TITLE
test(e2e): tag nightly builds

### PR DESCRIPTION
**Pull request by chriswldenyer**
Tag images produced by nightly builds as 'nightly'.
This is to allow mayastor-e2e-self-ci runs to run
against the most recent successful develop images.

### CODE REVIEW

**Comment by chriswldenyer** [comment]
bors try

**Review by blaisedias — APPROVED** [review]
LGTM

**Review by GlennBullingham — APPROVED** [review]

**Comment by chriswldenyer** [comment]
bors merge

**Comment by chriswldenyer** [comment]
bors merge

**Comment by chriswldenyer** [comment]
bors try

**Comment by chriswldenyer** [comment]
bors try

**Comment by chriswldenyer** [comment]
bors try-

**Comment by chriswldenyer** [comment]
bors try

**Review by blaisedias — APPROVED** [review]
Looks okay to me.

**Comment by chriswldenyer** [comment]
bors merge

**Review by GlennBullingham — APPROVED** [review]

**Pull request merged**
