### PR TITLE
chore(mayastor): remove code to create metadata index on "MayaMeta" partition

### PR DESCRIPTION
**Pull request by cjones1024**
Do not create a metadata index on the "MayaMeta" partition for persisting
state of each child, as this information is now stored in etcd.

### CODE REVIEW

**Review by paulyoong — APPROVED** [review]

**Review by tiagolobocastro — APPROVED** [review]

**Comment by cjones1024** [comment]
bors try

**Review by gila — APPROVED** [review]

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors merge

**Pull request merged**
