### PR TITLE
chore: rearrange bins & set default

### PR DESCRIPTION
**Pull request by Hoverbear**
This PR shuffles around some of our `src/bin`
folder to match the layout from
https://doc.rust-lang.org/cargo/guide/project-layout.html.

It also sets a `default-run` to 
`mayastor-client` as most users will want that as 
a default I suspect.

There should not be any behavior changes other than
possibly some logs having
a new filename.

### CODE REVIEW

**Review by jkryl — APPROVED** [review]

**Review by tiagolobocastro — APPROVED** [review]

**Review by mtzaurus — APPROVED** [review]

**Comment by gila** [comment]
bors merge

**Comment by Hoverbear** [comment]
I think that's an unrelated failure?

@bors retry

**Comment by Hoverbear** [comment]
bors merge

**Comment by Hoverbear** [comment]
bors merge

**Pull request merged**
