### PR TITLE
CAS-574 and CAS-509  Refactored e2e disconnect tests

### PR DESCRIPTION
**Pull request by chriswldenyer**
End-to-end testing: Refactored e2e disconnect tests.

Refactored e2e disconnect tests for more reliable clean up on error.
Reduced duplicated code.
The three-node tests are combined into a single test.
The four-node test remains separate.
Disconnect setup and teardown are no longer tests on their own.
Static variables are moved into a struct.

### CODE REVIEW

**Review by blaisedias — APPROVED** [review]
LGTM

**Review by arne-rusek — APPROVED** [review]
Thank you! LGTM

**Comment by gila** [comment]
Please fixup the commit message @chriswldenyer

**Comment by chriswldenyer** [comment]
bors merge

**Pull request merged**
