### PR TITLE
chore(snapshot): add success log for nexus create snapshot

### PR DESCRIPTION
**Pull request by hrudaya21**

### CODE REVIEW

**Review by tiagolobocastro — APPROVED** [review]

**Review by dsharma-dc — APPROVED** [review]

**Comment by hrudaya21** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
One more, should the trace when we receive the request be info?
bors cancel

**Review by mtzaurus — APPROVED** [review]

**Comment by hrudaya21** [comment]
> One more, should the trace when we receive the request be info? bors cancel

okay. let me make the request as well info.

**Comment by hrudaya21** [comment]
bors merge

**Pull request merged**
