### PR TITLE
Update malloc.rs

### LINKED ISSUE #1484: compile error in io-engine/src/bdev/malloc.rs:172:23
When build vanilla v2.3 (on arm(!)) I got:

Compiling crossbeam-sync v0.0.0
error[E0308]: mismatched types
   --> io-engine/src/bdev/malloc.rs:172:23
    |
172 |                 name: cname.as_ptr() as *mut i8,
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `u8`, found `i8`
    |
    = note: expected raw pointer `*mut u8`
               found raw pointer `*mut i8`

Which I fixed with: https://github.com/bhuism/mayastor/commit/fc330d50035e40346e3490741d4f7aa654bacb8b

d'you want a pr for this on development? ( I forked v2.3 )

(after this io-engine build was 100% fine btw)

### PR DESCRIPTION
**Pull request by bhuism**
Fixes #1484

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
Thanks @bhuism, same comment as previous PR if you don't mind.

**Comment by bhuism** [comment]
@tiagolobocastro sure thing, done

**Comment by tiagolobocastro** [comment]
> @tiagolobocastro sure thing, done

Sorry one more, first letter of subject must be lower case Compile -> compile

**Comment by tiagolobocastro** [comment]
Also could you please be a bit more specific on the commit message and specify that it's for your cpu, arm64 was it?

**Comment by bhuism** [comment]
@tiagolobocastro done

**Comment by tiagolobocastro** [comment]
bors try

**Review by dsharma-dc — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
@bhuism  this fails the build for x64:
```
172 |                 name: cname.as_ptr() as *mut u8,

    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i8`, found `u8`
```

I suspect the correct fix is this which should ensure correct type is used for both platform:
```rust
name: cname.as_ptr() as *mut std::os::raw::c_char,
```
Would you be able to test this?

**Comment by bhuism** [comment]
@tiagolobocastro done

**Comment by bhuism** [comment]
@tiagolobocastro sorry for the wrong branch commit on README.md

**Comment by tiagolobocastro** [comment]
> @tiagolobocastro done

Thank you.
bors try

**Review by tiagolobocastro — APPROVED** [review]
Thank you @bhuism !
bors merge

**Pull request merged**
