### PR TITLE
chore: update file metadata Dockerfile

### PR DESCRIPTION
**Pull request by orville-wright**
Tiny change to force update to file metadata date

Signed-off-by: Orville Wright <orville.wright@yahoo.com>

### CODE REVIEW

**Comment by sinhaashish** [comment]
Please update the commit message , to something like this `chore: update metadata file` for the lint commit to pass.

**Comment by orville-wright** [comment]
thank @sinhaashish  - I couldn't figure out how to edit the Commit message from the web app interface, so had to do it via cmd line.
The PR checks looks healthier now.

**Comment by orville-wright** [comment]
Hey @sinhaashish can you review & approve please. This is for our CNCF Sandbox application, so it's important for the project status. If you need to chat with @avishnu, @niladrih or @Abhinandan-Purkait ... they can update you on why this is needed.

**Comment by edrob999** [comment]
Approved. :thumbsup:
Signed-off-by: Ed Robinson <ed.robinson@gmail.com>

**Review by edrob999 — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by sinhaashish — APPROVED** [review]

**Comment by orville-wright** [comment]
bors try

**Comment by orville-wright** [comment]
bors merge

**Pull request merged**
