### PR TITLE
fix(ci): remove debug flag

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Remove inadvertently checked in debug flag
Remove the commented out debug code as we now have the deployer tool
 to create control plane clusters.

### CODE REVIEW

**Review by arne-rusek — APPROVED** [review]
LGTM

**Review by paulyoong — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
