### PR TITLE
test(e2e): build and use on-demand k8s cluster

### PR DESCRIPTION
**Pull request by arne-rusek**
Adds a parallel pipeline branch to tests where it builds k8s cluster,
runs e2e tests on it and destroys the cluster it if tests succeed.

CAS-570

### CODE REVIEW

**Comment by arne-rusek** [comment]
bors try

**Comment by arne-rusek** [comment]
bors try-

**Comment by arne-rusek** [comment]
Tested in https://mayastor-ci.mayadata.io/job/Mayastor/job/test-jenkins/24/ (failed but no due to on-demand cluster - so asking for a review).

**Comment by arne-rusek** [comment]
bors try

**Review by blaisedias — COMMENTED** [review]
AFAICT, the clusters are always destroyed, whereas we would like to preserve the cluster on e2e test failure.

**Comment by arne-rusek** [comment]
> AFAICT, the clusters are always destroyed, whereas we would like to preserve the cluster on e2e test failure.

E2E tests are run in what Jenkins calls sequential stages (see e.g. [here](https://stackoverflow.com/questions/59688963/sequential-stages-within-parallel-pipeline-in-jenkins)) when a step fails in the sequential stage, next steps are not run. Also as e2e tests have been a bit unstable lately I have tested it numerous times. See e.g. [here](https://mayastor-ci.mayadata.io/job/Mayastor/job/test-jenkins/25/consoleFull). 
2021-01-26_105252 12_sshot

**Review by blaisedias — APPROVED** [review]

**Review by tiagolobocastro — APPROVED** [review]

**Review by jkryl — APPROVED** [review]

**Comment by arne-rusek** [comment]
bors merge

**Comment by arne-rusek** [comment]
bors merge

**Pull request merged**
