### PR TITLE
chore(release): update image tags to v.1.0.3

### PR DESCRIPTION
**Pull request by GlennBullingham**
Update container image tags in deployment yaml to reflect release v1.0.3

Signed-off-by: GlennBullingham <glenn.bullingham@datacore.com>

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
Think you should change this file https://github.com/openebs/mayastor/blob/release/1.0/scripts/check-deploy-yamls.sh as well. If you do then the pre-commit hook should then update the deploy accordingly.

**Review by blaisedias — APPROVED** [review]

**Comment by GlennBullingham** [comment]
bors merge

**Comment by GlennBullingham** [comment]
bors try

**Review by niladrih — APPROVED** [review]

**Review by tiagolobocastro — APPROVED** [review]

**Comment by GlennBullingham** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
