### PR TITLE
build: set openebs as image registry

### PR DESCRIPTION
**Pull request by pchandra19**

### CODE REVIEW

**Review by avishnu — APPROVED** [review]
lgtm

**Review by tiagolobocastro — APPROVED** [review]

**Comment by pchandra19** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Review by mtzaurus — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors ping

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by pchandra19** [comment]
bors merge

**Pull request merged**
