### PR TITLE
fix(host-devices): extend allowed major list

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Extends major list with the Local/Experimental 240-254 range and 255 reserved.

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
Resolves #1739

**Review by dsharma-dc — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by Abhinandan-Purkait** [comment]
@tiagolobocastro Are we sure pools can be created on those devices?

**Comment by tiagolobocastro** [comment]
> @tiagolobocastro Are we sure pools can be created on those devices?

As long as it's a block device don't see why not. We're not stopping anyone today as we don't check this when creating the pool itself, it just changes the "available" reported on the plugin.

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
