### PR TITLE
chore: force date metadata update on LICENSE file

### PR DESCRIPTION
**Pull request by orville-wright**
Trivial 1 char change to force data metadata update on file 
Change ``` http``` to ```https``` (which is actually important IHMO)

Signed-off-by: Orville Wright <orville.wright@yahoo.com>

### CODE REVIEW

**Comment by orville-wright** [comment]
@tiagolobocastro @avishnu @Abhinandan-Purkait @niladrih 
My PR's are constantly being trapped by ``` commitlint ``` failures ...
- Where can I find a readme that describes what the LINTER rules are for PR's and Commit messages ?? - Seriously annoying.

**Comment by avishnu** [comment]
Can you amend the commit message to the below:
chore: force date metadata update on file

Standard linter rules https://github.com/conventional-changelog/commitlint

**Comment by orville-wright** [comment]
bor merge

**Comment by orville-wright** [comment]
Thanks for the link  to linter rules. I'm very grateful for that.

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by edrob999 — APPROVED** [review]
:thumbsup:
Signed-off-by: Ed Robinson <ed.robinson@gmail.com>

**Comment by edrob999** [comment]
DCO signoff (Option-D)
:thumbsup:
Signed-off-by: Ed Robinson <ed.robinson@gmail.com>

**Review by avishnu — APPROVED** [review]

**Comment by orville-wright** [comment]
bors merge

**Pull request merged**
