### PR TITLE
test(py): add precommit hooks and pytest-bdd 

### PR DESCRIPTION
**Pull request by gila**

### CODE REVIEW

**Review by paulyoong — COMMENTED** [review]
There appears to be a number of empty files. Was this intended?

**Comment by gila** [comment]
> There appears to be a number of empty files. Was this intended?

They are not empty, GH just reports nonsense here.

**Review by tiagolobocastro — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
> > There appears to be a number of empty files. Was this intended?
> 
> They are not empty, GH just reports nonsense here.

It does actually report the permissions change. Rather than "Empty file. " it should just display nothing, that would be clearer I think.

**Review by paulyoong — APPROVED** [review]

**Pull request merged**
