### PR TITLE
fix(nvmx): controller attach context shall be a standalone raw pointer

### PR DESCRIPTION
**Pull request by mtzaurus**
NVMx controller attach context is now directly accessed via a standalone raw pointer.

### CODE REVIEW

**Comment by mtzaurus** [comment]
bors try

**Comment by mtzaurus** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]
I verified this fixes the bug I was hitting :+1:

**Review by hrudaya21 — APPROVED** [review]

**Comment by mtzaurus** [comment]
bors merge

**Pull request merged**
