### PR TITLE
fix(snapshot): fix alloc value for thick and thin provisioned lvol when snapshot is created from it (Cherrypick #1452)

### PR DESCRIPTION
**Pull request by hrudaya21**

### CODE REVIEW

**Review by tiagolobocastro — APPROVED** [review]

**Comment by hrudaya21** [comment]
bors try

**Comment by tiagolobocastro** [comment]
You need to rebase and resolve conflicts, btw just spotted  a typo: thik/thick

**Comment by hrudaya21** [comment]
> You need to rebase and resolve conflicts, btw just spotted a typo: thik/thick

Yes. Kept the latest hash from spdk which is merged today. Changed the typo.

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by mtzaurus — APPROVED** [review]

**Comment by hrudaya21** [comment]
bors merge

**Pull request merged**
