### PR TITLE
ci: add develop-release GH action

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Updates submodules to the release branch.

### CODE REVIEW

**Review by hrudaya21 — APPROVED** [review]

**Review by dsharma-dc — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
Surely not related to this..
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
