### PR TITLE
447 Initialise tracing so that default subscriber filtering may be configured via environment variable.

### PR DESCRIPTION
**Pull request by cjones1024**
Create an EnvFilter for the default subscriber that allows the filter to be configured via the RUST_LOG environment variable.
This reproduces as closely as possible the old behaviour using the logging crate.
The default logging level is honoured *only* if RUST_LOG is not set (to a valid value).

### CODE REVIEW

**Review by jonathan-teh — APPROVED** [review]
Looks fine but you should remove the "CAS-" prefix from the commit message as that's a different numbering system.

**Review by tiagolobocastro — APPROVED** [review]

**Comment by cjones1024** [comment]
> 
> 
> Looks fine but you should remove the "CAS-" prefix from the commit message as that's a different numbering system.

Yes, have realized that. will amend accordingly when merging into develop

**Comment by jonathan-teh** [comment]
Commit messages need to be changed and pushed first though as bors does a merge commit.

**Pull request merged**
