### PR TITLE
fix(jsonrpc): revert change to reformat output from jsonrpc subcommand

### PR DESCRIPTION
**Pull request by cjones1024**
Revert previous change

### CODE REVIEW

**Comment by cjones1024** [comment]
Revert previous change so that, for example, we have well formed output
```
{
  "fields": {
    "major": 21,
    "minor": 1,
    "patch": 0,
    "suffix": ""
  },
  "version": "SPDK v21.01"
}
```
rather than
```
{
  "result": "{\n  \"fields\": {\n    \"major\": 21,\n    \"minor\": 1,\n    \"patch\": 0,\n    \"suffix\": \"\"\n  },\n  \"version\": \"SPDK v21.01\"\n}"
}
```

**Review by paulyoong — APPROVED** [review]

**Review by tiagolobocastro — APPROVED** [review]
Is there another output type or is it always json?

**Review by Hoverbear — APPROVED** [review]

**Comment by cjones1024** [comment]
> 
> 
> Is there another output type or is it always json?

It was only ever json. Note that, while the -o option is now accepted it doesn't actually modify the behaviour.

**Comment by cjones1024** [comment]
bors merge

**Comment by cjones1024** [comment]
bors merge

**Pull request merged**
