### PR TITLE
fix(ci): generate hostnqn if host does not have one

### PR DESCRIPTION
**Pull request by tiagolobocastro**

### CODE REVIEW

**Review by paulyoong — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors ping

**Pull request merged**
