### PR TITLE
feat: configure for direnv via envrc

### PR DESCRIPTION
**Pull request by Hoverbear**
This PR enables [`direnv`](https://direnv.net/) users to, when changing into the directory:

* (For the first time) See that we have an `.envrc` file. They can then type `direnv allow .` to give permission to their system to autoload the `.envrc`.
* Have `direnv`, a tool which has a shell hook, load the requisite `shell.nix` automatically.

This is beneficial to users who use `direnv` (which I understand is common in the nix world) as once a user has configured this, they no longer need to type `nix-shell` to activate their environment. Some users also use IDE tools like [VSCode direnv](https://marketplace.visualstudio.com/items?itemName=Rubymaniac.vscode-direnv) for this.

# To test

Try adding `direnv` to your package set ([don't forget to add the hook to your shell]( https://direnv.net/docs/hook.html)).

Then, `cd` into your Mayastor directory from a different one. It might do some extra work, but your output should look like this:

```bash
[ana@architect:~/git/openebs]$ cd Mayastor/
direnv: loading ~/git/openebs/Mayastor/.envrc
direnv: using nix
direnv: using cached derivation
direnv: eval /home/ana/git/openebs/Mayastor/.direnv/cache-pre262347.257cbbcd3ab
direnv: export +AR +AR_FOR_TARGET +AS +AS_FOR_TARGET +CC +CC_FOR_TARGET +CONFIG_SHELL +CXX +CXX_FOR_TARGET +DETERMINISTIC_BUILD +HOST_PATH +IN_NIX_SHELL +LD +LD_FOR_TARGET +LIBCLANG_PATH +NIX_BINTOOLS +NIX_BINTOOLS_FOR_TARGET +NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_BINTOOLS_WRAPPER_TARGET_TARGET_x86_64_unknown_linux_gnu +NIX_BUILD_CORES +NIX_BUILD_TOP +NIX_CC +NIX_CC_FOR_TARGET +NIX_CC_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_CC_WRAPPER_TARGET_TARGET_x86_64_unknown_linux_gnu +NIX_CFLAGS_COMPILE +NIX_CFLAGS_COMPILE_FOR_TARGET +NIX_ENFORCE_NO_NATIVE +NIX_HARDENING_ENABLE +NIX_INDENT_MAKE +NIX_LDFLAGS +NIX_LDFLAGS_FOR_TARGET +NIX_PKG_CONFIG_WRAPPER_TARGET_TARGET_x86_64_unknown_linux_gnu +NIX_STORE +NM +NM_FOR_TARGET +NODE_PATH +OBJCOPY +OBJCOPY_FOR_TARGET +OBJDUMP +OBJDUMP_FOR_TARGET +PKG_CONFIG_FOR_TARGET +PKG_CONFIG_PATH_FOR_TARGET +PROTOC +PROTOC_INCLUDE +PYTHONHASHSEED +PYTHONNOUSERSITE +PYTHONPATH +RANLIB +RANLIB_FOR_TARGET +READELF +READELF_FOR_TARGET +SIZE +SIZE_FOR_TARGET +SOURCE_DATE_EPOCH +SPDK_PATH +STRINGS +STRINGS_FOR_TARGET +STRIP +STRIP_FOR_TARGET +TEMP +TMP +TMPDIR +__ETC_PROFILE_SOURCED +buildInputs +builder +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +doCheck +doInstallCheck +hardeningDisable +name +nativeBuildInputs +nobuildPhase +out +outputs +patches +phases +propagatedBuildInputs +propagatedNativeBuildInputs +shell +shellHook +stdenv +strictDeps +system ~PATH

[ana@architect:~/git/openebs/Mayastor]$ cd ..
direnv: unloading
```

Now you should be able to skip running `nix-shell` to enter your dev environment.

### CODE REVIEW

**Review by paulyoong — APPROVED** [review]
Nice, thanks.

**Comment by gila** [comment]
@Hoverbear Thank you, I've not used vscode for, well no real reason actually but over the weekend I thought I give it a swirl and see how good the rust-analyser plugin makes it. 

So far so good, and I've also used the nix-env selector (BTW vscode now nix elf-patches binaries downloaded from the internet).  I have one question perhaps you might have an idea for/on. We have arguments in our `shell.nix`: 

1. Local SPDK means that if you `spdk-sys/spdk` checked out locally, we will use that local copy to build against that one from our fork.

2. Option two is `no-rust`, which means "use whatever rust I have locally installed", instead of fetching it. 

We always used to have (1) by default where spdk-sys was a submodule. However, this was (a) time consuming (b) confusing for people who are not used to submodules. 

In any case, my local version looks like this:
```bash
> $ cat .envrc
use nix --arg nospdk true --arg norust true
```

To avoid "personal preference" to be picked up then, should we add something to .envrc with a comment that states, something towards the extent of:

```bash
# If you want to configure certain options for your .envrc and don't
# want git to track that change you can either use: 
#  (1)  ~/.gitignore (which is global)
#  (2) `git update-index --assume-unchanged .envrc
```

Despite that, LGTM!

**Review by gila — APPROVED** [review]

**Comment by Hoverbear** [comment]
Ah yeah! Agree! Let me add that. :)

**Pull request merged**
