### PR TITLE
fix(nexus): fixing child retire during rebuild

### PR DESCRIPTION
**Pull request by dsavitskiy**

### CODE REVIEW

**Comment by dsavitskiy** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
CI was borked..
bors try

**Review by mtzaurus — APPROVED** [review]

**Comment by dsavitskiy** [comment]
bors try

**Comment by dsavitskiy** [comment]
bors merge

**Comment by dsavitskiy** [comment]
bors merge

**Comment by dsavitskiy** [comment]
bors merge

**Comment by dsavitskiy** [comment]
bors try

**Comment by tiagolobocastro** [comment]
Odd, seems like the python tests are taking 3h to complete!

**Comment by tiagolobocastro** [comment]
Can you look into this before merging @dsavitskiy ? This would severely affect our CI given we have only 1 system to run the python tests atm..

**Comment by dsavitskiy** [comment]
Yes sure, I won't be merging this. I was sure that I fixed the stuck python test but obviously it is not the case.
I won't bors try again before the release is done, as it affects CI.

**Comment by dsavitskiy** [comment]
bors try

**Comment by dsavitskiy** [comment]
bors try

**Comment by dsavitskiy** [comment]
bors try

**Comment by dsavitskiy** [comment]
bors merge

**Pull request merged**
