### PR TITLE
feat(rest client): add support for new rest calls

### PR DESCRIPTION
**Pull request by paulyoong**
Add rest client support and test cases for calling JSON gRPC methods and
listing block devices.

Resolves: CAS-732

### CODE REVIEW

**Review by tiagolobocastro — APPROVED** [review]

**Review by jonathan-teh — APPROVED** [review]

**Comment by paulyoong** [comment]
bors try

**Comment by paulyoong** [comment]
bors merge

**Review by gila — APPROVED** [review]

**Comment by paulyoong** [comment]
bors merge

**Comment by paulyoong** [comment]
bors merge

**Comment by paulyoong** [comment]
bors merge

**Pull request merged**
