### PR TITLE
refactor: snapshot listing based on query

### PR DESCRIPTION
**Pull request by Abhinandan-Purkait**
### What does this PR do?
- Refactors the snapshot list by query feature.
- Changes the usage in the tests.

### Why do we need this PR?
- This simplifies the query and increases maitainability.

### CODE REVIEW

**Comment by Abhinandan-Purkait** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors ping

**Comment by tiagolobocastro** [comment]
bors try

**Comment by Abhinandan-Purkait** [comment]
bors try

**Review by hrudaya21 — APPROVED** [review]

**Review by tiagolobocastro — APPROVED** [review]

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Comment by Abhinandan-Purkait** [comment]
bors merge

**Pull request merged**
