### PR TITLE
refactor(moac): drop support for NBD in CSI

### PR DESCRIPTION
**Pull request by jkryl**
NBD does not work well with new nexus feature when nexus is created
only if it is used (mounted). For NBD we need to know which node the
nexus is located and the location must not change throughout the
lifetime of the volume. Apparently that does not work now when nexus
is created on whatever node is available and the location can change
between mounts of the volume.

And as part of that convert csi.js to typescript.

Resolves: CAS-672

### CODE REVIEW

**Review by gila — APPROVED** [review]
@Jan, oddly enough this song popped into my head when seeing this PR. It clearly shows I need to step away a bit :joy: 

https://www.youtube.com/watch?v=4jAyZ4njHsc

**Review by tiagolobocastro — APPROVED** [review]
> And Now His Watch Is Ended

**Comment by jkryl** [comment]
bors merge

**Comment by jkryl** [comment]
bors retry

**Comment by jkryl** [comment]
bors retry

**Pull request merged**
