### PR TITLE
chore: update chart to include nvmf env variables

### PR DESCRIPTION
**Pull request by tiagolobocastro**

### CODE REVIEW

**Review by paulyoong — APPROVED** [review]

**Review by GlennBullingham — APPROVED** [review]
LGTM

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
