### PR TITLE
test(e2e): run nightly on only one pipeline

### PR DESCRIPTION
**Pull request by chriswldenyer**
Ensure the nightly run happens on the 
Mayastor pipeline only.
The Mayastor-e2e pipeline currently shares this Jenkinsfile,
though for not much longer, until then ensure nightly runs occur
only on Mayastor pipeline.
Additionally, emit build tag to the XRay report description.

### CODE REVIEW

**Comment by chriswldenyer** [comment]
bors try

**Review by blaisedias — COMMENTED** [review]
LGTM

**Review by blaisedias — APPROVED** [review]
LGTM

**Review by GlennBullingham — APPROVED** [review]

**Comment by chriswldenyer** [comment]
bors merge

**Pull request merged**
