### PR TITLE
test(e2e): install loki on the cluster

### PR DESCRIPTION
**Pull request by chriswldenyer**
Install Loki on the cluster prior to each e2e test.
Remove Loki from the cluster when finished.
API key is stored as a Jenkins secret.

### CODE REVIEW

**Comment by chriswldenyer** [comment]
bors try

**Comment by chriswldenyer** [comment]
bors try

**Comment by chriswldenyer** [comment]
bors try

**Review by GlennBullingham — APPROVED** [review]

**Review by blaisedias — APPROVED** [review]

**Comment by chriswldenyer** [comment]
bors merge

**Comment by chriswldenyer** [comment]
bors merge

**Pull request merged**
