### PR TITLE
test(e2e): nightly test git sha

### PR DESCRIPTION
**Pull request by chriswldenyer**
Nightly e2e runs should run against the build
tagged with the git sha, not nightly.
Use new nightly profile for nightly runs.

### CODE REVIEW

**Comment by chriswldenyer** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]

**Comment by chriswldenyer** [comment]
bors try

**Review by blaisedias — APPROVED** [review]

**Comment by chriswldenyer** [comment]
bors merge

**Comment by chriswldenyer** [comment]
bors merge

**Comment by chriswldenyer** [comment]
bors merge

**Pull request merged**
