### PR TITLE
chore: add poolname in v1 grpc replica response

### PR DESCRIPTION
**Pull request by Ab-hishek**
Signed-off-by: Abhishek Agarwal <abhiagarwal.agarwal2@gmail.com>

### CODE REVIEW

**Review by Abhinandan-Purkait — APPROVED** [review]
LGTM

**Review by tiagolobocastro — APPROVED** [review]

**Comment by Ab-hishek** [comment]
bors merge

**Review by dsavitskiy — APPROVED** [review]

**Comment by Ab-hishek** [comment]
bors try

**Comment by Ab-hishek** [comment]
bors merge

**Comment by Ab-hishek** [comment]
bors merge

**Pull request merged**
