### PR TITLE
chore: split proto files and bump dependency

### PR DESCRIPTION
**Pull request by gila**

### CODE REVIEW

**Comment by gila** [comment]
bors try

**Comment by gila** [comment]
bors try

**Comment by gila** [comment]
bors try

**Comment by gila** [comment]
bors try

**Comment by gila** [comment]
bors try

**Comment by gila** [comment]
bors try

**Comment by gila** [comment]
bors try

**Comment by gila** [comment]
bors retry

**Review by paulyoong — APPROVED** [review]

**Review by mtzaurus — APPROVED** [review]

**Pull request merged**
