### PR TITLE
chore(rest): add openapi spec to the tree

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Add pre-commit hook to make sure we update the spec as we change the
 rest code.
Add another step to the CI linter to check that the spec is up to date.
(Note the linter here isn't quite right for this)

### CODE REVIEW

**Review by paulyoong — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Review by jkryl — APPROVED** [review]
Great! 🎉  That serves as an inspiration for me to do similar thing for our generated yaml files.

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
