### PR TITLE
feat(thin): passing thin flag down to spdk

### PR DESCRIPTION
**Pull request by dsavitskiy**

### CODE REVIEW

**Comment by dsavitskiy** [comment]
bors try

**Comment by dsavitskiy** [comment]
bors try

**Comment by dsavitskiy** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]
The control-plane test that checks thin true will finally pass :partying_face:

**Review by mtzaurus — APPROVED** [review]

**Comment by dsavitskiy** [comment]
bors merge

**Pull request merged**
