### PR TITLE
test: update python and grpc packages

### PR DESCRIPTION
**Pull request by tiagolobocastro**

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by abhilashshetty04 — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
