### PR TITLE
chore(snapshot): merge snapshot code to develop

### PR DESCRIPTION
**Pull request by mtzaurus**
merge snapshot code to develop

### CODE REVIEW

**Comment by mtzaurus** [comment]
bors try

**Comment by mtzaurus** [comment]
bors try

**Review by hrudaya21 — APPROVED** [review]

**Review by tiagolobocastro — APPROVED** [review]

**Comment by mtzaurus** [comment]
bors merge

**Comment by mtzaurus** [comment]
bors try

**Comment by mtzaurus** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by mtzaurus** [comment]
bors merge

**Comment by mtzaurus** [comment]
bors merge

**Comment by mtzaurus** [comment]
bors merge

**Pull request merged**
