### PR TITLE
test(python): add a 3rd nexus to an existing multipath device

### PR DESCRIPTION
**Pull request by jonathan-teh**
Create 2 nexuses each with 2 replicas, connect to both nexuses over
NVMf, run fio against the block device. While fio is running, create
a 3rd nexus with the same 2 replicas and connect to it over NVMf.
Verify that the existing block device now has 3 paths.

Fixes CAS-975

### CODE REVIEW

**Comment by jonathan-teh** [comment]
bors try

**Comment by jonathan-teh** [comment]
bors try

**Comment by jonathan-teh** [comment]
bors try-

**Comment by jonathan-teh** [comment]
bors try

**Comment by jonathan-teh** [comment]
bors try

**Comment by jonathan-teh** [comment]
bors try

**Review by mtzaurus — APPROVED** [review]

**Comment by jonathan-teh** [comment]
bors try

**Review by cjones1024 — APPROVED** [review]

**Comment by jonathan-teh** [comment]
bors merge

**Review by paulyoong — APPROVED** [review]

**Pull request merged**
