### PR TITLE
fix(casperf): subcommand is not required

### PR DESCRIPTION
**Pull request by tiagolobocastro**
bonus: make URI required

### CODE REVIEW

**Review by hrudaya21 — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
