### PR TITLE
fix(cli): controller cli command added

### PR DESCRIPTION
**Pull request by mtzaurus**
Introduced a new command for listing nvme controllers.

Implements CAS-918

### CODE REVIEW

**Review by tiagolobocastro — APPROVED** [review]
Would it be possible to show outstanding IOs to a controller?

**Comment by gila** [comment]
> Would it be possible to show outstanding IOs to a controller?

That would be interesting to know indeed because I would imagine that we would use this tool if a controller is acting up. Could we traverse the IO channels and collect those stats?

**Comment by mtzaurus** [comment]
We can add I/O stats for the controllers on behalf of a separate command - 'controller stats' or so.  Would that work ?

**Comment by mtzaurus** [comment]
I created a separate ticket for tracking I/O stats for nvme controllers: "CAS-950 Want CLI for displaying I/O stats for NVMe controllers"

**Review by gila — APPROVED** [review]

**Pull request merged**
