### PR TITLE
ci: ensure fmt fails on jenkins

### PR DESCRIPTION
**Pull request by tiagolobocastro**

### CODE REVIEW

**Review by dsharma-dc — APPROVED** [review]

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
