### PR TITLE
Limit number of layers in docker images to avoid problems.

### PR DESCRIPTION
**Pull request by jkryl**

### CODE REVIEW

**Review by tiagolobocastro — APPROVED** [review]

**Review by paulyoong — APPROVED** [review]

**Review by GlennBullingham — APPROVED** [review]
42 layers is within the 56 limited identified in the root cause https://github.com/containerd/containerd/blob/master/pkg/cri/server/image_pull.go#L493 so all should be good.

**Comment by jkryl** [comment]
bors merge

**Comment by jkryl** [comment]
bors retry

**Comment by jkryl** [comment]
bors retry

**Comment by jkryl** [comment]
bors retry

**Review by gila — APPROVED** [review]

**Comment by jkryl** [comment]
bors retry

**Pull request merged**
