### PR TITLE
refactor(ctrl-plane): tidy up the control-plane

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Reorganize the control-plane components in the repo by moving them to a
 separate control-plane directory.
Rename the services into agents.

Build the control plane components as a separate derivation with a lot
 less dependencies which reduces the build type.
Create unique derivation for each control plane component.
Make use of these components on the container image which reduces the
 image size.

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
Seems like a lot, but most of the files were just moved...

**Review by paulyoong — APPROVED** [review]

**Review by chriswldenyer — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
