### PR TITLE
chore(git): fixing git commit hooks

### PR DESCRIPTION
**Pull request by dsavitskiy**
Signed-off-by: Dmitry Savitskiy <dmitry.savitskiy@datacore.com>

### CODE REVIEW

**Comment by dsavitskiy** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]

**Review by mtzaurus — APPROVED** [review]

**Review by felix1209 — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
This change is already on develop

**Pull request closed without merging**
