### PR TITLE
fix(ci): openapi-check should fail

### PR DESCRIPTION
**Pull request by tiagolobocastro**
The pre-commit gives this for free but not on Jenkins so check manually
 if the spec files changed.

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
Testing Jenkins without the spec checked in:bors try

**Comment by tiagolobocastro** [comment]
Testing Jenkins without the spec checked in:
bors try

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
should now pass with the updated spec:
bors try

**Comment by tiagolobocastro** [comment]
> should now pass with the updated spec:
> bors try

It passed the linter stage now :+1:

**Review by paulyoong — APPROVED** [review]

**Review by jonathan-teh — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
