### PR TITLE
fix(spdk-sys): work around layout issue with spdk_nvme_feat_async_event_configuration

### PR DESCRIPTION
**Pull request by jonathan-teh**
Mark spdk_nvme_feat_async_event_configuration as an opaque type.
Also includes a chore to update bindgen and other crates.

### CODE REVIEW

**Comment by jonathan-teh** [comment]
bors try

**Comment by jonathan-teh** [comment]
bors try

**Comment by jonathan-teh** [comment]
bors try-

**Comment by jonathan-teh** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]

**Review by cjones1024 — APPROVED** [review]

**Comment by jonathan-teh** [comment]
bors merge

**Pull request merged**
