### PR TITLE
chore(rpc): move rpc to seperate repo

### PR DESCRIPTION
**Pull request by gila**
This allows sharing the rpc crate and the proto files cross repo's.

### CODE REVIEW

**Comment by gila** [comment]
bors try

**Comment by gila** [comment]
bors try

**Comment by gila** [comment]
bors cancel

**Comment by gila** [comment]
bors retry

**Comment by mtzaurus** [comment]
I have a generic question about new repository: https://github.com/gila/rpc.
Is it a temporary location ? Should put it in Mayastor Git namespace ?

**Comment by gila** [comment]
I'm just trying something out here. But I don't like it...

**Pull request closed without merging**
