### PR TITLE
chore: upgrade cargo deps

### PR DESCRIPTION
**Pull request by tiagolobocastro**
todo: upgrade clap as require more code changes across various binaries

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors try

**Review by hrudaya21 — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Review by dsharma-dc — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
