### PR TITLE
CAS-495 Include more callsite information in trace events.

### PR DESCRIPTION
**Pull request by cjones1024**
- Created custom formatter for default subscriber to include
   additional information such as file and line number.

 - Custom formatter will also only generate ansi escape sequences to display LEVEL in colour
   if stdout is attached to a terminal.

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]
I would change the format slightly from
[2020-11-16T10:58:42.181733780+00:00 DEBUG mayastor::subsys::nvmf::target] (target.rs:292) enabling discovery for target
to
[2020-11-16T10:58:42.181733780+00:00 DEBUG mayastor::subsys::nvmf::target::target.rs:292] enabling discovery for target
but that'd just be my personal preference :)

**Review by jonathan-teh — APPROVED** [review]

**Review by mtzaurus — APPROVED** [review]

**Comment by cjones1024** [comment]
> 
> 
> I would change the format slightly from
> [2020-11-16T10:58:42.181733780+00:00 DEBUG mayastor::subsys::nvmf::target] (target.rs:292) enabling discovery for target
> to
> [2020-11-16T10:58:42.181733780+00:00 DEBUG mayastor::subsys::nvmf::target::target.rs:292] enabling discovery for target
> but that'd just be my personal preference :)

There is a reason for the separation. The format of the message line is actually the following:
[TIMESTAMP LEVEL TARGET] CONTEXT (LOCATION) MESSAGE

Now the CONTEXT part will *only* be present for spans/instrumented functions.

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors check

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors merge

**Pull request merged**
