### PR TITLE
Jenkinsfile simplification

### PR DESCRIPTION
**Pull request by bobek**
First iteration in effort to simplify our `Jenkinsfile`. My [test project](https://mayastor-ci.mayadata.io/job/bobek-test/) behaved really well.

@jkryl

### CODE REVIEW

**Comment by arne-rusek** [comment]
This looks good.

**Review by jkryl — APPROVED** [review]
Looks good. thanks!

**Review by arne-rusek — APPROVED** [review]
LGTM

**Comment by jkryl** [comment]
bors merge

**Pull request closed without merging**
