### PR TITLE
feat(tests): integrating support for v1 api in tests

### PR DESCRIPTION
**Pull request by dsavitskiy**

### CODE REVIEW

**Comment by dsavitskiy** [comment]
Here's PR for mayastor-dependencies submodule: https://github.com/openebs/mayastor-dependencies/pull/6

**Comment by dsavitskiy** [comment]
bors try

**Comment by dsavitskiy** [comment]
The problem with my commit is that I had to copy v1 API module definitions from data plane repo (rpc/src/lib.rs directory) to Composer.
I think, we should improve there: probably, put all these definitions into mayastor-api repo, and use them from Composer, data plane, etc.

**Review by tiagolobocastro — APPROVED** [review]

**Comment by dsavitskiy** [comment]
I pushed the update version with v1 namespace definitions moved into mayastor-api repo. Here's the corresponding PR: https://github.com/openebs/mayastor-dependencies/pull/6.

**Comment by dsavitskiy** [comment]
bors try

**Comment by dsavitskiy** [comment]
PR for mayastor-api: https://github.com/openebs/mayastor-api/pull/20
PR for mayastor-dependencies: https://github.com/openebs/mayastor-dependencies/pull/6

**Review by Abhinandan-Purkait — APPROVED** [review]

**Comment by dsavitskiy** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]

**Review by mtzaurus — APPROVED** [review]

**Comment by dsavitskiy** [comment]
bors merge

**Pull request merged**
