### PR TITLE
fix: io-engine clippy warnings

### PR DESCRIPTION
**Pull request by hrudaya21**
Signed-off-by: Hrudaya <hrudayaranjan.sahoo@datacore.com>

### CODE REVIEW

**Comment by mtzaurus** [comment]
bors cancel

**Comment by mtzaurus** [comment]
bors try

**Comment by hrudaya21** [comment]
bors try

**Comment by dsavitskiy** [comment]
bors try

**Comment by hrudaya21** [comment]
bors try

**Comment by hrudaya21** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors delegate

**Comment by tiagolobocastro** [comment]
bors d+

**Comment by dsavitskiy** [comment]
bors try

**Comment by hrudaya21** [comment]
bors try

**Comment by hrudaya21** [comment]
bors try

**Comment by hrudaya21** [comment]
bors try

**Comment by hrudaya21** [comment]
bors try

**Pull request closed without merging**
