### PR TITLE
chore(hugepage): add 1GB Hugepage checking

### PR DESCRIPTION
**Pull request by dong-liuliu**
Using 2MB Hugepage is the common case, but in some enviroment, Hugepage is enabled on size 1GB.
So also check whether 1GB page is enough to run Mayastor.

### CODE REVIEW

**Review by tiagolobocastro — APPROVED** [review]

**Review by mtzaurus — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
@dong-liuliu could you please rename your commit and pr from `chare` to `chore`?

**Comment by dong-liuliu** [comment]
Sure, Tiago. Fixed this typo. :)

**Comment by tiagolobocastro** [comment]
> Sure, Tiago. Fixed this typo. :)
thank you :)

bors merge

**Comment by tiagolobocastro** [comment]
bors try

**Comment by dong-liuliu** [comment]
> @dong-liuliu could you please run the lint against your commit? `nix-shell --run ./scripts/rust-style.sh ci.nix`

Thank you, Tiago.

**Comment by dong-liuliu** [comment]
hi, @tiagolobocastro 
I've tried to compile and run "nix-shell --run ./scripts/rust-style.sh ci.nix" several times without error.
Really confused on the build failure reported by bors. But I couldn't look inside CI failure link.
Are there any method for me to know what error caused failure in mayastor CI?

**Comment by dong-liuliu** [comment]
> oh sorry for wasting your time, it's `rust-linter.sh` that's failing and not `rust-style.sh` :(
Never mind~ Applied linter revisement.

**Comment by tiagolobocastro** [comment]
bors try

**Comment by dong-liuliu** [comment]
Hi, @tiagolobocastro Could you give me more indication about the failure Bors reported?

**Comment by tiagolobocastro** [comment]
> Hi, @tiagolobocastro Could you give me more indication about the failure Bors reported?

CI is running out of space -.- I cleaned up some space, let's try again
bors try

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by dong-liuliu** [comment]
Thank you so much @tiagolobocastro

**Pull request merged**
