### PR TITLE
ci(gha): fix submodule check

### PR DESCRIPTION
**Pull request by tiagolobocastro**
Ensures we fetch git history and submodules.

### CODE REVIEW

**Review by Abhinandan-Purkait — APPROVED** [review]

**Review by hrudaya21 — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
weird ssl error, don't think anything to do with this PR... let's try again
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
