### PR TITLE
chore: update bytes, derive_builder, env_logger, http-body, udev, uuid

### PR DESCRIPTION
**Pull request by jonathan-teh**
Update bytes (0.5 to 1.0), derive_builder (0.7 to 0.10), env_logger
(0.7 to 0.8), http-body (0.2 to 0.4), udev (0.4 to 0.6) and uuid (0.7
to 0.8), and fix up build issues due to API changes.

Also update pin-project-lite to 0.2.6 as 0.2.4 was yanked.

### CODE REVIEW

**Comment by jonathan-teh** [comment]
bors try

**Review by tiagolobocastro — APPROVED** [review]

**Review by gila — APPROVED** [review]
Tanks!

**Comment by jonathan-teh** [comment]
bors merge

**Comment by jonathan-teh** [comment]
bors merge

**Pull request merged**
