### PR TITLE
Pull rpc from dependencies submodule and various fixes

### PR DESCRIPTION
**Pull request by tiagolobocastro**
feat: silence traces from unwanted modules
    
    Follows same pattern as control-plane.
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---    

    refactor: pull rpc from dependencies
    
    Move to latest dependencies submodule and pull the rpc from there.
    This also upgrades tonic/prost to latest versions.
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    fix(io-engine-client): add subcommand required message
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

---

    fix(rebuild): don't report skipped segments as transferred
    
    When a segment is unallocated then we should not include this segment for transferred stats.
    This addresses an issue where for an empty thin volume the transferred bytes were being shown
    as the entire volume size.
    
    Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
Some tests might need to be fixed, let's see:
bors try

**Review by dsavitskiy — APPROVED** [review]

**Review by dsharma-dc — APPROVED** [review]

**Review by hrudaya21 — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
