### PR TITLE
chore(test): validate remaining pytest tests

### PR DESCRIPTION
**Pull request by cjones1024**
Include all current pytests in scripts/pytest-tests.sh.

Identify, and temporarily disable, those tests that
are currently failing and require additional work.

### CODE REVIEW

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
The following tests are excluded, as they are currently failing:
- test_cli_controller (2nd test fails due to error during teardown)
- test_rpc
- test_multi_nexus
- test_nexus
- test_null_nexus

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors try

**Review by gila — CHANGES_REQUESTED** [review]
There seems to be an empty file? Also, is there a reason we reduce the number of nexus volumes from 100 to 3?

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
> 
> 
> There seems to be an empty file? Also, is there a reason we reduce the number of nexus volumes from 100 to 3?

There were a couple of files that had changes to their permissions only (the test_*.py files should not be executable).
The nunber of GUIDs/volumes was actually 10 rather than 3. This was initially an oversight in that my development VM could not cope with 100. However, after adding extra memory/CPUs/hugepages, I still cannot get this test to run with the full 100.  It also appears to be failing for the same reason when run in the Jenkins pipeline. The main issue seems to be that pytest is capturing the log output in memory, and this test is generating a *lot* of messages. I am hoping that pytest can be coerced into writing the output generated directly to files rather than caching in memory, but I need to investigate this further.  Have disabled this test for now, and will raise a separate Jira/PR to address the resource issues.

**Comment by cjones1024** [comment]
bors try

**Review by jonathan-teh — APPROVED** [review]
Nice refactoring for commonality and readability.
There were some changes to `test_nexus_resv_key` to bring the test up-to-date, which I'd overlooked in #980 and #1002.

**Comment by zeenix** [comment]
> The following tests are excluded, as they are currently failing:
> 
>     * test_cli_controller
> 
>     * test_rpc
> 
>     * test_nexus_multipath

Ah, so I wasn't alone there after all. :) How come the CI is not failing? :thinking:

**Comment by cjones1024** [comment]
> 
> 
> > The following tests are excluded, as they are currently failing:
> > ```
> > * test_cli_controller
> > 
> > * test_rpc
> > 
> > * test_nexus_multipath
> > ```
> 
> Ah, so I wasn't alone there after all. :) How come the CI is not failing? 🤔

There are only two tests remaining that are failing. They are test_rpc and test_null_nexus. These and a number of other tests were not included in the "CI" script that invokes the tests as they were relying of an additional VM in which to connect to the published taqrgets and run fio. 
The purpose of this particular PR is to remove that requirement and ensure that all existing tests will be included in the CI pipeline.
This is now the case with the exception of the two tests mentioned above.

**Comment by cjones1024** [comment]
> 
> 
> There seems to be an empty file? Also, is there a reason we reduce the number of nexus volumes from 100 to 3?

The number of nexuses has now been set to 10 in order to ensure that the test passes while I am currently investigating why the test fails with much larger number of nexues.

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors try

**Comment by cjones1024** [comment]
bors try

**Review by gila — APPROVED** [review]

**Comment by cjones1024** [comment]
bors merge

**Comment by cjones1024** [comment]
bors try

**Pull request merged**
