### PR TITLE
Enabled missed tests from control plane

### PR DESCRIPTION
**Pull request by tiagolobocastro**

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors retry

**Comment by tiagolobocastro** [comment]
bors retry

**Review by chriswldenyer — APPROVED** [review]
LGTM

**Review by paulyoong — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
