### PR TITLE
fix(ci): wa jenkins bug where params are not set on first run

### PR DESCRIPTION
**Pull request by tiagolobocastro**
https://issues.jenkins.io/browse/JENKINS-41929

Make sure we always run the tests.

### CODE REVIEW

**Comment by tiagolobocastro** [comment]
bors try

**Review by mtzaurus — APPROVED** [review]

**Comment by tiagolobocastro** [comment]
bors cancel
bors try

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors try

**Review by chriswldenyer — APPROVED** [review]
So if the parameters are undefined, they are forced to "true" ?
LGTM IIUIC

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
> So if the parameters are undefined, they are forced to "true" ? LGTM IIUIC

I'm not sure, I think that they are undefined, which is what I'm trying to find out why my test commit.
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
bors try

**Comment by tiagolobocastro** [comment]
@chriswldenyer looks like the param is `null` so I'll test for that instead of "".

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors cancel

**Comment by tiagolobocastro** [comment]
bors merge

**Pull request merged**
