### PR TITLE
test(e2e): support for coverage builds

### PR DESCRIPTION
**Pull request by chriswldenyer**
Allow optional building of a coverage-enabled
version of mayastor image. Option --coverage
added to release.sh.
Use mayastor image as host for mayastor-csi
for CI testing.

### CODE REVIEW

**Review by gila — APPROVED** [review]

**Review by zeenix — CHANGES_REQUESTED** [review]
> Use mayastor image as host for mayastor-csi for CI testing

You mean it continues to use existing image or now uses the new coverage-enabled image? If former, the commit log can be improved a bit so it's clear which image you're referring to here. If latter, should be also split into it's own commit as it's a separate logical change.

**Comment by chriswldenyer** [comment]
> > Use mayastor image as host for mayastor-csi for CI testing
> 
> You mean it continues to use existing image or now uses the new coverage-enabled image? If former, the commit log can be improved a bit so it's clear which image you're referring to here. If latter, should be also split into it's own commit as it's a separate logical change.

I am splitting this PR into 2 changes. Raised new PR https://github.com/openebs/mayastor/pull/1013/files to use mayastor image when deploying both mayastor and mayastor-csi which I will merge first. The coverage changes will be applied on top of that.

**Comment by zeenix** [comment]
> I am splitting this PR into 2 changes. Raised new PR https://github.com/openebs/mayastor/pull/1013/files to use mayastor image when deploying both mayastor and mayastor-csi which I will merge first. The coverage changes will be applied on top of that.

Cool. Not an objection at all since smaller PRs are better for sure but just to clarify, that's not what I meant. I was only talking about splitting the commits. You were probably not in that meeting but we discussed and agreed that multiple commits per PR are fine but commits should be atomic. Anyway, all good. Just wanted to clarify. :)

**Review by zeenix — CHANGES_REQUESTED** [review]
Unless I'm missing something, I'm still seeing 3 logical changes:

* Allow optional building of a coverage-enabled version of mayastor image.
* Option --coverage added to release.sh.
* Use mayastor image as host for mayastor-csi for CI testing.

i-e separate commits for each desired.

**Pull request closed without merging**
