### PR TITLE
test: pod remove test fixes

### PR DESCRIPTION
**Pull request by chriswldenyer**
Remove test storage class and pending items.
Make test independent of number of nodes.
Reduce number replicas in test 3->2
Remove local-only tests.
Use logf to output progress

### CODE REVIEW

**Review by blaisedias — CHANGES_REQUESTED** [review]
Please add AfterEach clauses for each test, move cleanup from AfterSuite to AfterEach clauses and invoke AfterEachCheck ( if appropriate )

**Review by paulyoong — APPROVED** [review]

**Comment by chriswldenyer** [comment]
> Please add AfterEach clauses for each test, move cleanup from AfterSuite to AfterEach clauses and invoke AfterEachCheck ( if appropriate )

Now done.

**Review by blaisedias — APPROVED** [review]
LGTM

**Comment by chriswldenyer** [comment]
bors merge

**Comment by chriswldenyer** [comment]
bors merge

**Comment by chriswldenyer** [comment]
bors merge

**Pull request merged**
