### PR TITLE
fix(build): added libunwind dependency for release builds

### PR DESCRIPTION
**Pull request by mtzaurus**
Added explicit libunwind dependency for release builds.

Signed-off-by: Mikhail Tcymbaliuk <mtzaurus@gmail.com>

### CODE REVIEW

**Review by blaisedias — APPROVED** [review]
LGTM

**Review by tiagolobocastro — APPROVED** [review]

**Comment by mtzaurus** [comment]
bors merge

**Comment by mtzaurus** [comment]
bors merge

**Comment by tiagolobocastro** [comment]
bors merge

**Comment by mtzaurus** [comment]
bors try

**Comment by mtzaurus** [comment]
bors merge

**Pull request merged**
