### PR TITLE
test: volume expand with snapshots present

### PR DESCRIPTION
**Pull request by dsharma-dc**

### CODE REVIEW

**Review by dsavitskiy — APPROVED** [review]

**Comment by dsharma-dc** [comment]
bors try

**Review by dsavitskiy — APPROVED** [review]

**Comment by dsharma-dc** [comment]
@tiagolobocastro We can go ahead merging this now.

**Review by tiagolobocastro — APPROVED** [review]
Would be good to add some more tests for multiple snapshots with multiple resizes? Not sure what the current coverage is on this repo, ie do we have bdd's for snapshots here?

**Comment by dsharma-dc** [comment]
> Would be good to add some more tests for multiple snapshots with multiple resizes? Not sure what the current coverage is on this repo, ie do we have bdd's for snapshots here?

I don't see we are adding any bdds in this repo since most of the new tests are now composer based cargo tests? I did test with multiple snaps and resize, I'll add one against a new ticket(already created) because it'll take some time to modify the test structure accordingly.

**Comment by dsharma-dc** [comment]
bors try

**Comment by dsharma-dc** [comment]
bors merge

**Comment by dsharma-dc** [comment]
bors merge

**Pull request merged**
