### PR TITLE
test(e2e): use loki_run_id to identify runs in Loki MQ-612

### PR DESCRIPTION
**Pull request by chriswldenyer**
When using a Loki query "run=<build_no>" is ambiguous,
because branches and pipelines use independent
sequences of build numbers.
Instead of the build number, construct a string based on:
pipeline + branch + build number.
e.g. "Mayastor-develop-456"

### CODE REVIEW

**Comment by chriswldenyer** [comment]
bors try

**Comment by chriswldenyer** [comment]
bors try

**Comment by chriswldenyer** [comment]
bors try-

**Comment by chriswldenyer** [comment]
bors try

**Review by blaisedias — APPROVED** [review]
LGTM

**Comment by chriswldenyer** [comment]
bors merge

**Review by arne-rusek — APPROVED** [review]
LGTM, just missing ticket ID in PR, added

**Comment by chriswldenyer** [comment]
> LGTM, just missing ticket ID in PR, added

Thanks!

**Comment by chriswldenyer** [comment]
bors merge

**Pull request merged**
